title = "TOML File"

[owner]
name = "Chen Scheim"
dob = 1997-05-27T07:32:00-08:00

[limits]
days_ago = 60

[constants]
zero = 0
one = 1
space = ' '
line = '\r\n'
txt = '.txt'
wild = '*'
multiprocess = 20
company_limit = 500
write = 'w'
append = 'a'
read = 'r'
utf8 = 'utf-8'

[signatures]
signs = ['<script>document.body.innerHTML=\'.*\'</script>',
    '<script src=\"http.?:\/\/.*\.js\"></script>',
    '<script src=\"http.?:\/\/.*>',
    '<form method=\"POST\".*>',
    '<iframe src=\"http.?:\/\/.*\"><\/iframe>',
    '<iframe src=\"http.?:\/\/.*>',
    '<object data=\"http.?:\/\/.*>',
    '<embed type=\".*\" src=\"http.?:\/\/.*>',
    '<embed src=\"http.?:\/\/.*>',
    '127.0.0.1\/',
    '\.\./\.\./',
    '\\\.\.\\\.\.',
    '<script>eval\(function\(.*</script>',
    '<script>eval\(unescape\(.*</script>',
    'document\.write\(.?<iframe src=.*</iframe>',
    '＜script＞document\.body.*</script>']
archive = ['<button id=\".*\" onclick=\".*\">']
js_signs = ['eval(']
exceptions = ['gif',
    'png',
    'png/',
    'svg',
    'ico',
    'jpg',
    'pic1',
    'videoImg',
    'logo',
    'image',
    'webp',
    'gif/',
    'woff2',
    'woff']
result_filtering = ['archive.org',
    'googlecode.com',
    'googleoptimize.com',
    'cloudflare.com',
    'surveygizmo.com',
    'maxcdn.com',
    'spotify.com']
[urls]
blacklist_url = ['https://malwareworld.com/textlists/suspiciousDomains.txt',
    'https://malwareworld.com/textlists/suspiciousIPs.txt']