title = "TOML File"

[owner]
name = "Chen Scheim"

[limits]
days_ago = 60

[constants]
zero = 0
one = 1
under = '_'
line = '\r\n'
txt = '.txt'
html = '.html'
wild = '*'
multiprocess = 1000
company_limit = 2323
write = 'w'
append = 'a'
read = 'r'
utf8 = 'utf-8'
vt_api = '42273d6479030971ddb208428ec9a768fd05d5e29e0125b5a80c1bdd7d995275'

[signatures]
signs = ['<script>document.body.innerHTML=\'.*\'</script>',
    '<script src=\"http.?:\/\/.*\.js\"></script>',
    '<script src=\"http.?:\/\/.*>',
    '<form method=\"POST\".*>',
    '<iframe src=\"http.?:\/\/.*\"><\/iframe>',
    '<iframe src=\"http.?:\/\/.*>',
    '<object data=\"http.?:\/\/.*>',
    '<embed type=\".*\" src=\"http.?:\/\/.*>',
    '<embed src=\"http.?:\/\/.*>',
    '127.0.0.1\/',
    '/\.\./\.\./',
    '\\\.\.\\\.\.',
    '<script>eval\(function\(.*</script>',
    '<script>eval\(unescape\(.*</script>',
    'document\.write\(.?<iframe src=.*</iframe>',
    '＜script＞document\.body.*</script>']
js_signs = ['eval(']
exceptions = ['gif',
            'png',
            'png/',
            'svg',
            'ico',
            'jpg',
            'pic1',
            'videoImg',
            'logo',
            'image',
            'webp',
            'gif/',
            'woff2',
            'woff']
result_filtering = ['archive.org',
    'googleapis.com',
    'googlecode.com',
    'googleoptimize.com',
    'cloudflare.com',
    'cloudfront.net',
    'surveygizmo.com',
    'maxcdn.com',
    'spotify.com',
    'github.com',
    'jsdelivr.net',
    'cludo.com',
    'fontawesome.com',
    'unpkg.com']
mimetype = ['text/css',
    'text/html',
    'text/javascript',
    'application/x-httpd-php',
    'application/rtf']
archive = ['<button id=\".*\" onclick=\".*\">']

[urls]
blacklist_url = ['https://malwareworld.com/textlists/suspiciousDomains.txt',
    'https://malwareworld.com/textlists/suspiciousIPs.txt']