title = "TOML File"

[owner]
name = "Chen Scheim"
dob = 1997-05-27T07:32:00-08:00

[signatures]
signs = ['<script>document.body.innerHTML=\'.*\'</script>']
exceptions = ['gif',
    'png',
    'svg',
    'ico',
    'jpg',
    'pic1',
    'videoImg',
    'logo',
    'image',
    'webp',
    'gif/']